"""Add workflow automation models

Revision ID: 18408d214be8
Revises: 242015d851b4
Create Date: 2026-03-04 14:24:16.789319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18408d214be8'
down_revision = '242015d851b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('job_closing_reminder', 'interview_reminder', 'application_followup', 'document_reminder', 'status_update', 'report_generation', 'cleanup', name='task_types'), nullable=False),
    sa.Column('task_config', sa.JSON(), nullable=True),
    sa.Column('schedule_type', sa.Enum('once', 'daily', 'weekly', 'monthly', name='schedule_types'), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.Enum('status_change', 'time_based', 'score_based', 'document_submitted', 'interview_scheduled', 'interview_completed', 'job_closing', name='trigger_types'), nullable=False),
    sa.Column('trigger_status', sa.String(length=50), nullable=True),
    sa.Column('trigger_days', sa.Integer(), nullable=True),
    sa.Column('trigger_score', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('change_status', 'send_email', 'send_notification', 'assign_reviewer', 'create_task', 'schedule_reminder', name='action_types'), nullable=False),
    sa.Column('action_status', sa.String(length=50), nullable=True),
    sa.Column('action_template_id', sa.Integer(), nullable=True),
    sa.Column('action_config', sa.JSON(), nullable=True),
    sa.Column('condition_job_id', sa.Integer(), nullable=True),
    sa.Column('condition_min_score', sa.Integer(), nullable=True),
    sa.Column('condition_max_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_template_id'], ['message_templates.id'], ),
    sa.ForeignKeyConstraint(['condition_job_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_transition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.Enum('manual', 'automated', 'system', name='change_types'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workflow_rule_id', sa.Integer(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_rule_id'], ['workflow_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=True),
    sa.Column('action_taken', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'skipped', name='execution_status'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['workflow_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_executions')
    op.drop_table('status_transition_logs')
    op.drop_table('workflow_rules')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
